# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.CharField(max_length=1000),
        ),
    ]
