# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170402_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
