# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('accesslevel', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('depatment', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('base_salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
            ],
        ),
    ]
