# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20170404_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
