# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_month',
            field=models.FileField(default='/media/norecord.txt', upload_to=b''),
        ),
        migrations.AddField(
            model_name='user',
            name='oldest_month',
            field=models.FileField(default='/media/norecord.txt', upload_to=b''),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_month',
            field=models.FileField(default='/media/norecord.txt', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
