# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_auto_20170412_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oldest_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='previous_month',
        ),
    ]
