# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_auto_20170422_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
